package com.example.Kursach.controller;
import java.util.*;

import com.example.Kursach.model.Deposit;
import com.example.Kursach.model.LogIn;
import com.example.Kursach.model.User;
import com.example.Kursach.repository.UserRepository;
import com.example.Kursach.service.DepositService;
import com.example.Kursach.service.LogInService;
import com.example.Kursach.service.UserService;
import org.apache.catalina.core.ApplicationContext;
import org.hibernate.service.spi.InjectService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;


@RestController
@RequestMapping("/api/v1")
public class UserController {

    // This means to get the bean called userRepository
    @Autowired     // Which is auto-generated by Spring, we will use it to handle the data
private UserService userService;
    @Autowired
    private DepositService depositService;
    @Autowired
    private LogInService logInService;
    @CrossOrigin
    @GetMapping("/login")
    public List<LogIn>getAllLogins(){return logInService.findAll();}
    //show all clients
    @CrossOrigin
    @GetMapping("/users")
    public List<User> getAllUsers() {
        return userService.findAll();
    }

    //show all deposits
    @CrossOrigin
    @GetMapping("/deposits")
    public List<Deposit> getAllDeposits() {
        return depositService.findAll();
    }

    //show a client
    @GetMapping("/users/{id}")
    public Optional<User> getUser(@PathVariable(value = "id") int Id) {
        return userService.findById(Id);
    }
    @CrossOrigin

    //show client deposits
    @GetMapping("/users/{id}/deposits")
    public List<Deposit> getDeposits(@PathVariable(value = "id")int Id){
       return userService.findById(Id).get().getDepositList();
    }

    //add a client deposit
    @CrossOrigin
    @PostMapping("/users/{id}/deposits")
    public Deposit addDeposit(@PathVariable(value = "id") int Id,@Valid @RequestBody Deposit deposit){
        deposit.setUser( userService.findById(Id).get());
        //userService.findById(Id).get().getDepositList().add(deposit);
        return depositService.addDeposit(deposit);
    }

    //delete a client deposit
    @CrossOrigin
    @DeleteMapping("/users/{c_id}/deposits/{id}")
    public void deleteDeposit(@PathVariable(value = "c_id") int clientId,@PathVariable(value = "id") int Id)
    {userService.findById(clientId).get().getDepositList().remove(depositService.findById(Id).get());
        depositService.deleteDeposit(Id);
    }

    //update a client deposit
    @CrossOrigin
    @PutMapping("/users/{c_id}/deposits/{id}")
    public Deposit updateDeposit(@PathVariable(value = "c_id") int clientId,@PathVariable(value = "id") int Id,@Valid @RequestBody Deposit deposit){
        deposit.setUser( userService.findById(clientId).get());
        //userService.findById(Id).get().getDepositList().add(deposit);
        return depositService.updateDeposit(Id,deposit);}
        //add a client
        @CrossOrigin
    @PostMapping("/users")
    public User addUser(@Valid @RequestBody User user)
    { return userService.addUser(user);}

    //update a client
    @CrossOrigin
    @PutMapping("/users/{id}")
    public User updateUser(@PathVariable(value = "id") int Id,@Valid @RequestBody User user)
    {
        return userService.updateUser(Id,user);
    }

    //delete a client
    @CrossOrigin
    @DeleteMapping("/users/{id}")
    public void deleteUser(@PathVariable(value = "id") int Id)
    {userService.deleteUser(Id);
    }
}