package com.example.Kursach.controller;
import java.util.*;

import com.example.Kursach.model.User;
import com.example.Kursach.repository.UserRepository;
import com.example.Kursach.service.UserService;
import org.apache.catalina.core.ApplicationContext;
import org.hibernate.service.spi.InjectService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;


@RestController
@RequestMapping("/api/v1")
public class UserController {

    // This means to get the bean called userRepository
    @Autowired     // Which is auto-generated by Spring, we will use it to handle the data
private UserService userService;

    @CrossOrigin
    @GetMapping("/users")
    public List<User> getAllUsers() {
        return userService.findAll();
    }
    @CrossOrigin
    @PostMapping("/users")
    public User addUser(@Valid @RequestBody User user)
    { return userService.addUser(user);}
    @PutMapping("/users/{id}")
    public User updateUser(@PathVariable(value = "id") int Id,@Valid @RequestBody User user)
    {
        return userService.updateUser(Id,user);
    }
    @CrossOrigin
    @DeleteMapping("/users/{id}")
    public void deleteUser(@PathVariable(value = "id") int Id)
    {userService.deleteUser(Id);
    }
}